### ISSUE TITLE
question: execute app

### ISSUE THREAD

**Issue by Arnold1** [sfreiberg/simplessh#2]
Hi,

how can you start an app which i uploaded with `func (c *Client) Upload(local, remote string) error` before?

the app will be uploaded to the /home directory and i need to start it via ./myapp 1

**Comment by sfreiberg** [comment]
Have you tried using:

(c *Client) Exec(cmd string) ([]byte, error)

An example would be:

out, err := client.Exec("./myapp 1")

**Comment by Arnold1** [comment]
ok, will try.

also how can you upload a file to the /home directory?

**Comment by sfreiberg** [comment]
You listed the function call in your first post. An example is pretty straightforward:

err := client.Upload("/path/to/local/file", "~/filename.txt")

**Comment by Arnold1** [comment]
works. thanks!

**Comment by Arnold1** [comment]
i tried on windows 7:
```
> go get github.com/sfreiberg/simplessh
package golang.org/x/crypto/ssh: unrecognized import path "golang.org/x/crypto/s
sh"
```

any idea about that issue?

**Comment by sfreiberg** [comment]
Is your GOPATH variable set to a valid directory?

On Tue, Jun 9, 2015 at 3:05 AM, Arnold1 notifications@github.com wrote:

> i tried on windows 7:
> 
> > go get github.com/sfreiberg/simplessh
> > package golang.org/x/crypto/ssh: unrecognized import path "golang.org/x/crypto/s
> > sh"
> 
> any idea about that issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sfreiberg/simplessh/issues/2#issuecomment-110300054.

## 

Sam Freiberg
- samueldean@gmail.com
  +- http://www.darkaslight.com/

**Comment by Arnold1** [comment]
fixed it, the problem was that the proxy server settings where not visible to git....
